### ISSUE TITLE
Llamadas a funciones

### ISSUE THREAD

**Issue by jazcarate** [sisoputnfrba/2016-1c-Elestac-enunciado#1]
https://github.com/sisoputnfrba/foro/issues/224

En el enunciado:
`t_puntero_instruccion llamarFuncion(t_nombre_etiqueta etiqueta, t_posicion donde_retornar, t_puntero_instruccion linea_en_ejecuccion)`

En el parser:
`void (*AnSISOP_llamarSinRetorno)(t_nombre_etiqueta etiqueta)`
y
`void (*AnSISOP_llamarConRetorno)(t_nombre_etiqueta etiqueta, t_puntero donde_retornar)`

**Comment by mgarciaisaia** [comment]
@jazcarate ¿Considerás que es algo errateable esto? ¿Qué corregirías?

**Comment by jazcarate** [comment]
Si solo se usan llamadas con retorno; pondría la firma de `AnSISOP_llamarConRetorno` :dancers:

**Comment by mgarciaisaia** [comment]
Be my guest :)​
