### ISSUE TITLE
Incongruencia en el el enunciado

### ISSUE THREAD

**Issue by nicogon** [sisoputnfrba/2016-1c-Elestac-enunciado#11]
En la configuracion del nucleo habla de

SEM_IDS
IO_IDS

pero en el ejemplo que dan (que muchos como yo harán copy paste)

IO_ID=[Disco, Impresora, Scanner]
SEM_ID=[SEM1, SEM2, SEM3]

Notese que falta la S -> io_idS sem_idS.

**Comment by nicogon** [comment]
ah y otra duda que tenia. puedo incluir otras cosas en el archivo de configuración? ej IP UMC?

**Comment by pabloacvd** [comment]
Hola!
Nosotros tuvimos el mismo problema y la misma duda.

Por un lado, nuestro archivo de configuración es igual al del ejemplo, nos pareció lo más lógico :-P
**IO_ID**=[Disco, Impresora, Scanner]
**SEM_ID**=[SEM1, SEM2, SEM3]

También agregamos algunos datos adicionales al archivo de configuración (sobre todo IPs y puertos, para facilitarnos las pruebas y no tener que volver a compilar cada vez que cambiamos de red).

Me sumo entonces con las mismas dudas y agrego:
En la entrega final, ¿vamos a usar nuestros archivos de configuración y programas o nos van a proveer de distintos archivos para poner a prueba el sistema?

_Esto definirá si podemos extender los archivos de configuración o dejarlos como el enunciado._

Gracias.-

@sisoputnfrba/vamo-a-calmarno

**Comment by tferraro** [comment]
Buenas!

Esto corre más para el foro que para un issue perdido en el repo del foro :wink:. De todas maneras, los archivos de configuración serán los que armen ustedes. Las únicas restricciones es que tienen que  terminar de ser configurados por ustedes en la entrega (por un tema de las IPs y Puertos) y que sean cuidadosos con las entradas extras que agreguen, que no sean redundantes o que vayan en contra del enunciado.

Saludos!
