### ISSUE TITLE
Error en primitiva irAlLabel

### ISSUE THREAD

**Issue by damianvc31** [sisoputnfrba/2016-1c-Elestac-enunciado#12]
Cito al enunciado:

> **7. irAlLabel**
> Devuelve el número de la primer instrucción ejecutable de etiqueta y -1 en caso de error.
> `t_puntero_instruccion irAlLabel(t_nombre_etiqueta etiqueta)`

Encontramos dos errores en esto. 
1. t_puntero_instruccion esta definido como uint, por lo que no podria devolver -1
2. En el parser, la primitiva devuelve void. Lo cual tiene sentido por lo que entiendo que debe hacer la primitiva.

Asi que nos quedamos con la version del parser.

**Comment by tferraro** [comment]
Resolved by #15
