### ISSUE TITLE
Primitiva ansisop #14 (signal)

### ISSUE THREAD

**Issue by marcofbb** [sisoputnfrba/2016-1c-Elestac-enunciado#19]
Al declararla de esta forma

```
void signal(t_nombre_semaforo identificador_semaforo)
```

Te da el siguiente error: " error: too many arguments to function ‘signal’", en consecuencia tuve que re-nombrarla a `void parser_signal(t_nombre_semaforo identificador_semaforo)`

**Comment by mgarciaisaia** [comment]
¡Aloha!

El problema que tuviste es que, claro, la función `signal` ya está definida en C (es parte de la standard library de C, que se linkea con todos los programas por defecto). Lo que te dice el compilador es que vos declaraste una función `signal` que sólo recibe un `t_nombre_semaforo`, y al momento de linkear le das una función `signal` que recibe un `int` y un puntero a función - ¡no matchean!

La solución, como bien hiciste, es usar otro nombre para tu función. Pero, ojo, eso no es "un bug" del enunciado ni nada por el estilo - el parser no limita el nombre de tu función; lo único que te pide es que se la pases en el campo correspondiente de la estructura que tiene todos los punteros a las primitivas.

En C hay un único "namespace" de funciones - es decir, todas las funciones de un programa tienen que tener nombres únicos. En otros lenguajes se usan los `namespace`, `package`, `module` y similares para permitir esto, pero C por ahora no lo tiene. Por eso es que la mayoría de las bibliotecas tienen un prefijo para el nombre de las funciones - piensen en `pthread_create`, `sem_wait`, `list_add`, etc. Es una convención que, cuando venimos del mundo de objetos y lenguajes un poco más modernos, parece fea, pero existe y es el estándar _de facto_ porque tiene sentido que así sea.
